name: 4casters-bot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.23.5
  - matplotlib=3.6.3
  - scipy=1.10.0
  - scikit-learn=1.2.1
  - tqdm=4.64.1
  - pandas=2.2.2
  #- xgboost=1.7.5
  - selenium=4.12.0
  #- nba_api=1.4.1
  - seaborn=0.12.2
  - unidecode=1.3.7
  #- shap=0.44.1
  #- undetected-chromedriver=3.5.3
  - webdriver-manager=4.0.0
  - pip
  - ipykernel=6.29.5
  #- pyarrow=17.0.0
  #- fastparquet=2024.5.0
  #- hyperopt=0.2.7
  #- ipywidgets=8.1.5